const lyricsBySource = {
  'TeknikGadjahMadaGitar.mp3': ['Teknik Gadjah Mada', 'Teknik Gadjah Mada slalu ada di hatiku', 'Menanglah menang kami bersamamu slalu ada mendukungmu'],
  'syalalaGitar.mp3': ['Syalalalalalalalalalala 2x', 'Ooooooooooo 2x', 'Amarah senyum, dan air mata, ku korbankan seluruh jiwa dan raga..', 'Lantunan doa, terus menggema, digdaya supersonik', 'Serang musuhmu, libas musuhmu, ku bela kau bela kau bela kau kau kau…', 'Serang lawanmu, bantai lawanmu, Jayalah kau teknikku', 'Oooo ooooo ooooo oooo ooo ooo oo oo..', 'oooo ooooo ooooo oooo ooo… (2x)'],
  'SupersonikYangKutungguGitar.mp3': ['Supersonik yang kutunggu- kutunggu Kunanti-nanti (CEWEK : EEE AAA)', 'Telah lama ku berdiri berdiri menari nari (CEWEK : EEE AAA)', 'Bila Teknik menang lagi ku gembira (SEMUA : SYALALALALALA)', 'Ku kan slalu mendukungmu setiap waktu'],
  'LaGrandeGitar.mp3': ['Ayo dukunglah teknik', 'Agar jadi JUARA', 'Kita kawal bersama tuk selama-lamanya', 'Ayo dukunglah teknik', 'Agar jadi JUARA', 'Kita kawal bersama tuk selama-lamanya', 'oole..oleo La grande storia (CEWEK : STORIAAAAA)', 'oole..oleo Siamo Noi', 'oole..oleo La bella gloria (COWOK : GLORIAAAAA)', 'oole..oleo Vinci per noi!!'],
  'KemenanganGitar.mp3': ['Kemenangan di depan mata', 'Percaya kita pasti bisa', 'Laga demi laga semangat membara', 'Ini saatnya kita juara', 'oo..oo..oo..oo'],
  'HariIniGitar.mp3': ['Hari ini ... Hari yang kutunggu tunggu', 'Kami datang mendukung ….. teknikku', 'Berjuanglah Jadilah yang nomor satu', 'Kami yakin teknikku jadi juara', 'Teknik Mania selalu gembira ria', 'Kita bersama dukung teknik ... Kita', 'Teknik ... Kita', 'Juara ... SATU!'],
  'BukalahMatamuGitar': ['Bukalah Matamu', 'Pasang Telingamu', 'Lihatlah kedepan', 'Bernyanyi Bersama', 'Kanan Bersuara', 'Kiri Bersuara', 'Satukan Suara', 'Dukung … Teknik', 'Ooooooo TEKNIK 4x'],
  'AyoBangGitar.mp3': ['Neng … ayo neng … ayo dukung … (voli) teknik (COWOK serentak)', 'Bang … ayo bang … ayo dukung … (voli) teknik (CEWEK serentak harus lebih kenceng)', 'Dari pada dukung yang lain...', 'Lebih baik dukung … (voli) teknik', '(voli) teknik ... oi ... jadi juara'],
  'weAreThe.wav': ['Memang ini milik kami yang hilang dari kami, Dan kini sudah kembali lagi..', 'Memang ini milik kami yang hilang dari kami, Dan kini sudah kembali lagi..', 'We are The Champion, kata Paman Freddie Mercury', 'We are The Champion, bukan sulap enggak pakai dukun', 'We are The Champion, Supersonik pasti jadi juara!!'],
  'andecaAndeci.wav': ['Senangnya dalam hati', 'Teknikku main lagi', 'Salam hangat dari kami ... Teknik Mania!', 'Kepada panitia .... Kami sayang padamu', 'Kepada (basket) teknik ... I say i love you', 'Andeca andeci la bora bora bori', 'Andeca andeci la bora bora bori'],
  'kamiPemenangnya.wav': ['Syalala lala, syalala lala', 'Syalala lalala', 'Ooooo oo, Ooooo oo', 'Oooo oooo', 'Eo Eo Eo, Teknik Gadjah Mada aaaa', 'Eo Eo Eo, Kita pemenang nya', 'Eo Eo Eo, Rayakan bersama', 'Eo Eo Eo, Kita Pesta Pora'],
  'kamiDatangLagi.wav': ['Teknik datang lagi', 'Teknik siap berjuang lagi', 'Kau terus berlari, tiga point hari ini', 'Satu jiwa hati', 'Kami datang tuk bernyayi', 'Satu nama Supersonik', 'Supersonik harga mati!', 'Forza Grande Teknikku Ale', 'Rossonero vicente', 'Forza Grande Teknikku Ale', 'Supersonik sampai mati!', 'Ale ale aleeeeee, Hu', 'Ale ale aleeeeee, Hu', 'Ale ale aleeeeee, Hu', 'Ale ale aleeeeee, Hu', 'Ale ale aleeeeee, Hu'],
  'terbaikUntukmu.wav': ['oooooooo...ooooooo...oooooooo...ooooooooooo', 'Kudatang disini berdiri tegak kembali', 'Teknik yang ku pandang', 'Dengarkan kami bernyanyi..', 'oooooooo...ooooooooo...ooooooooo...ooooooooooo', 'Tak pernah ku lelah kita tak akan menyerah', 'Tetaplah menjadi Teknik kebanggaan kami', 'Semua kan kuberikan..', 'Satukan semua tujuan..tuk menang..', 'SUPERSONIK !!!', 'Hilang lelahku saat kita bersama..', 'Berikan terbaik untukmu disana..', 'Bersinarlah bagai bintang yang berpijar diangkasa..', 'Hilang lelahku saat kita bersama..', 'Berikan terbaik untukmu disana', 'Bersinarlah bagai bintang yang berpijar diangkasa..', 'Ole.. Ole.. Olee..olee Supersonik Ole..oleee!', 'Ole.. Ole.. Olee..olee Supersonik Ole..oleee!'],
  'hitamHitam.wav': ['Biru-biru (Basket) Teknik', 'Hitam Hitam Supersonik', 'Maju terus pantang mundur (Basket) Teknik', 'Jadi juara', 'la la la lalalala', 'la la la lalalala', 'la la la lalalala', 'lalalala'],
  'supersonikTunjukkanAksimu.wav': ['Supersonik ..... tunjukkan aksimu', 'Supersonik ..... bantailah musuhmu', 'Kita dukung ….. teknik kita .. Oi', 'Sekarang dan selamanya ….. Teknik ..... Ayo bergembira', 'Syalala oooo... 2x', 'Oooo..oooo..oooooooo'],
  'seiringJejakLangkahku.wav': ['Seiring jejak langkahku mendukung …. Teknikku', 'Jangan pernah kau ragu kamilah pendukungmu!', 'Satukanlah tekadmu kobarkan semangatmu', 'Jadilah yang nomor satu itulah yang ku mau!', 'Ayo Teknikku jadilah juara, juara pertama di Porsenigama', 'Yo ayo ayo… Teknikku jadilah juara', 'Kami Supersonik mendukungmu..'],
  'syalalalaTunjukkan.wav': ['Syalala Syalala Syalalalalalala', 'Syalala Syalala Syalalalalalala … Oi!', 'Tunjukkan semangatmu kepada … teknik', 'Berikan yang terbaik kepada … teknik', 'Kami ini supersonik satu hati sampai mati', 'Kami jago di lapangan kami raja pertandingan', 'Siapa suruh lawan … teknik'],
  'kukibarkanBendera.wav': ['Ku…kibarkan bendera teknikku', 'Hari ini kita harus menang', 'Supersonik siap berpesta', 'Ku cinta teknikku selamanya (Yo ayo ayo ayo)', 'Ayo teknikku jadilah juara', 'Kita rayakan bersama', 'Terserah mereka kuhanya cinta teknikku', 'Kami selalu bersamamu'],
  'teknikSatu.wav': ['Teknik Satu', 'Kami datang', 'Mendukungmu selamanya', 'Syalalala…. Syalalala…. Syalalala', 'Syalalala….'],
  'kalauAkuTeknik.wav': ['Kalau aku teknik', 'Kamu mau apa', 'Kuberterimakasih kepada mama', 'Mama papa saya cinta supersonik', 'Semua Supersonik', 'Oaeo oaeo oaeo oaeo (2x)'],
  'ayoTeknikJaya.wav': ['Ayo teknik, tunjukan kehebatanmu', 'Oi 4x', 'Ayo Teknik', 'Ku kan selalu mendukungmu', 'Oi 4x', 'Ayo teknik', 'Hidup dan matiku', 'Ayo teknik jaya', 'Ayayayaya', 'Supersonik Mendukungmu', 'Ayo teknik jaya', 'Ayayayaya', 'Supersonik Mendukungmu'],
  'jiRoLuPat.wav': ['Ji… Ro… Lu… Pat…', 'Huu semeleketeha huha 3x', 'Ayo ayo ayo supersonik', 'ooo ooo ooo ooo'],
  'disiniSupersonik.wav': ['Disini Supersonik', 'Disana supersonik', 'Oh teknik 4x', 'Kamilah supersonik'],
  'yoAyoTeknikku.wav': ['Yo ayo ayo … teknik', 'Ku ingin kita harus menang …', 'Yo Ayo Ayo … teknik', 'Ku ingin kita harus menang (CEWEK : EEE AYO AYO AYO AYO)'],
  'sudahKubilang.wav': ['Sudah kubilang jangan lawan …(voli) teknik', 'Sekarang kamu merasakan akibatnya', 'Mendingan kamu diam dirumah saja', 'Duduk yang manis nonton di layar kaca', 'Siapa yang suruh lawan … (voli) teknik 2x'],
  'ambrolProtol.wav': ['Syalalalala Syalalalala', 'Syalala syalala syalala', 'Syalalala syalalalala', 'Syalala syalala syalala', 'Diatas tribun kami bernyanyi', 'Diatas tribun kami bergoyang', 'Untuk mendukung supersonik sampai mati', 'Demi kebanggan supersonik', 'Kami hanya ingin kemenangan', 'Syalalalala Syalalalala', 'Syalala syalala syalala', 'Syalalala syalalalala', 'Syalala syalala syalala', 'Diatas tribun kami bernyanyi', 'Diatas tribun kami bergoyang', 'Untuk mendukung supersonik sampai mati', 'Demi kebanggan supersonik', 'Kami hanya ingin kemenangan', 'Ambrol potol ... KON***', 'Syalalalala Syalalalala', 'Syalala syalala syalala', 'Syalalala syalalalala', 'Syalala syalala syalala'],
  'namaHewan.wav': ['Wedhus artinya kambing', 'Jaran artinya kuda', 'Iwak itu artinya ikan', '… (Fakultas lain) itu anjing'],
  'dudiDudiDam.wav': ['Dudidudidam dam dudidudidam', 'Dudidudidam dam dudidudidam', 'Kamu dukung siapa? Teknik', 'Teknik didukung siapa? Kami', 'Kami supersonik, kami dutung teknik', 'Teknik ayo digoyang azek azek azek', 'Teknik jadi juara? Satu', 'Lawannya pulang aja! pulang', 'Kami supersonik, Kami dukung teknik', 'Teknik jadi juara, satu satu satu', 'Obat cacing namanya combatrin', 'Supersonik lawannya pipisin', '….. mending pulang jaga lilin', 'Koyo sarimin']
};

const civilionLyrics = Object.fromEntries(Object.entries(lyricsBySource).map(([key, lines]) => [key, lines.map((line) => line.replace(/supersonik/gi, 'CIVILION'))]));
window.CIVILION_LYRICS = civilionLyrics;
window.CIVILION_TITLES = {
  'TeknikGadjahMadaGitar.mp3': 'Teknik Gadjah Mada',
  'syalalaGitar.mp3': 'Bela Kau',
  'SupersonikYangKutungguGitar.mp3': 'CIVILION yang Kutunggu',
  'LaGrandeGitar.mp3': 'La Grande Teknik',
  'KemenanganGitar.mp3': 'Kemenangan',
  'HariIniGitar.mp3': 'Hari Ini',
  'BukalahMatamuGitar': 'Bukalah Matamu',
  'AyoBangGitar.mp3': 'Ayo Bang Ayo Neng',
  'weAreThe.wav': 'We Are The Champion',
  'andecaAndeci.wav': 'Andeca Andeci',
  'kamiPemenangnya.wav': 'Pesta Pora',
  'kamiDatangLagi.wav': 'Teknik Datang Lagi',
  'terbaikUntukmu.wav': 'Terbaik Untukmu',
  'hitamHitam.wav': 'Biru-Biru (Basket) Teknik',
  'supersonikTunjukkanAksimu.wav': 'Tunjukkan Aksimu',
  'seiringJejakLangkahku.wav': 'Seiring Jejak Langkah (POZNAN DANCE)',
  'syalalalaTunjukkan.wav': 'Syalala Tunjukkan Semangatmu',
  'kukibarkanBendera.wav': 'Kukibarkan',
  'teknikSatu.wav': 'Teknik Satu',
  'kalauAkuTeknik.wav': 'Kalau Aku Teknik',
  'ayoTeknikJaya.wav': 'Teknik Jaya',
  'jiRoLuPat.wav': 'Ji Ro Lu Pat',
  'disiniSupersonik.wav': 'Disini CIVILION',
  'yoAyoTeknikku.wav': 'Eee Ayo Ayo Ayo',
  'sudahKubilang.wav': 'Jangan Lawan',
  'ambrolProtol.wav': 'Ambrol Protol',
  'namaHewan.wav': 'Nama Hewan dan Artinya',
  'dudiDudiDam.wav': 'Dudidudidam'
};
window.CIVILION_DEFAULT_TITLES = window.CIVILION_TITLES;
